users:
  - username: root
    password: !
    update_password: on_create
    comment: Default Root user
    shell: /bin/bash
    ssh_key: "{{ root_ssh_key }}"
    exclusive_ssh_key: yes
    use_sudo: yes
    use_sudo_nopass: yes
    user_state: present
    servers:
      - strapi
      - database

  - username: deploy
    password: !
    update_password: on_create
    comment: Application deploy user (automation)
    primarygroup: deploy
    shell: /bin/bash
    ssh_key: "{{ root_ssh_key }}"
    exclusive_ssh_key: no
    use_sudo: no
    use_sudo_nopass: no
    user_state: present
    servers:
      - strapi
      - database

  - username: devops
    password: !
    update_password: on_create
    comment: Developer Operations Service Account
    primarygroup: devops
    groups: deploy
    shell: /bin/bash
    ssh_key: "{{ root_ssh_key }}"
    exclusive_ssh_key: no
    use_sudo: yes
    use_sudo_nopass: yes
    user_state: present
    servers:
      - strapi
      - database
