---
- hosts: strapi
  become: false
  remote_user: deploy
  vars_files:
    - ../crypt_vars/strapi.yml
    - ../crypt_vars/database.yml
    - ../tf_vars/tf_vars.yml

  vars:
    ansistrano_deploy_to: "{{ application_dir }}"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: git
    ansistrano_git_repo: "{{ application_git }}"
    ansistrano_git_branch: "main"
    ansistrano_before_symlink_tasks_file: ../tasks/before-symlink-tasks.yml
    ansistrano_after_symlink_tasks_file: ../tasks/after-symlink-tasks.yml

  roles:
    - role: deploy
