- hosts: all
  become: false
  # become_method: sudo
  remote_user: root
  vars_files:
    - ./crypt_vars/all.yml
    - ./tf_vars/tf_vars.yml

  roles:
    - apt
    - users

  tasks:
    - name: Setup Devops SSH Keys
      authorized_key:
        user: devops
        state: present
        key: "{{ item }}"
      with_file:
        - ssh_keys/example_devops.pub
    - name: Setup Deploy SSH Keys
      authorized_key:
        user: deploy
        state: present
        key: "{{ item }}"
      with_file:
        - ssh_keys/example_devops.pub
        - ssh_keys/example_deploy.pub

- import_playbook: playbooks/strapi_database.yml
